version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "/TwitPoster"
      - "/TwitPoster.EmailSender"
      - "/TwitPoster.Functions"
      - "/TwitPoster.Shared"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      
  - package-ecosystem: 'terraform'
    directory: '/terraform'
    schedule:
      interval: 'daily'