version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "/TwitPoster"
      - "/TwitPoster.EmailSender"
      - "/TwitPoster.Chat"
    schedule:
      interval: "daily"
    groups:
      testcontainers:
        patterns:
          - "Testcontainers*"
      massTransit:
        patterns:
          - "MassTransit*"
      xunit:
        patterns:
          - "xunit*"
      microsoft:
        patterns:
          - "Microsoft.*"

  - package-ecosystem: "nuget"
    directories:
      - "/TwitPoster.Shared"
    schedule:
      interval: "daily"
      

  - package-ecosystem: "nuget"
    directories:
      - "/TwitPoster.Functions"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      
  - package-ecosystem: 'terraform'
    directory: '/terraform'
    schedule:
      interval: 'daily'
      
  - package-ecosystem: 'Docker'
    directory: '/'
    schedule:
      interval: 'daily'