name: Build and Deploy Azure Function

on:
  push:
    branches: ["master", "azure-function"]
    paths:
      - "TwitPoster.Functions/**"
      - ".github/workflows/azure-function.deploy.yml"
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'windows-oleksii-dev-1'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './TwitPoster.Functions/TwitPoster.Functions'
  DOTNET_VERSION: '8.x'

concurrency:
  group: ${{ github.workflow }}-deployment
  cancel-in-progress: false

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
          
      - name: 'Upload Build Artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: function-app-build
          path: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

  deploy:
    runs-on: windows-latest
    needs: build
    environment: prod
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Download Build Artifacts'
        uses: actions/download-artifact@v3
        with:
          name: function-app-build
          path: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}