name: Build artifacts

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["master", "feature/terraform-env"]
  workflow_dispatch:

permissions:
  contents: 'read'
  packages: 'write'

env:
  twitposter_image: 'ghcr.io/wallyrion/twitposter:${{github.sha}}'
  twitposter_emailsender_image: 'ghcr.io/wallyrion/twitposter-emailsender:${{github.sha}}'

jobs:
  detect_changes:
    outputs:
      build_twitposter: ${{ steps.changes.outputs.twitposter }}
      build_email_sender: ${{ steps.changes.outputs.email_sender }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            twitposter:
              - './TwitPoster/**'
            email_sender:
              - './TwitPoster.EmailSender/**'

      - if: steps.changes.outputs.temp == 'true'
        run: |
          echo "Changes were detected in 'temp/', running the step."
  
  build_twitposter:
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.build_twitposter == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Restore dependencies - TwitPoster
        run: dotnet restore ./TwitPoster
  
      - name: Build - TwitPoster
        run: dotnet build --no-restore ./TwitPoster -c Release
  
      - name: Test - TwitPoster
        env:
          ASPNETCORE_ENVIRONMENT: Production
        run: dotnet test --no-build --verbosity normal ./TwitPoster -c Release
  
      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: publish image
        run: dotnet publish ./TwitPoster/src/TwitPoster.Web/TwitPoster.Web.csproj /t:PublishContainer -r linux-x64
  
      - name: change image tag
        run: docker tag twitposter ${{ env.twitposter_image }}
  
      - name: Docker Push
        run: docker push ${{ env.twitposter_image }}
        
  build_email_sender:
    if: ${{ needs.detect_changes.outputs.build_email_sender == 'true' }}
    needs: detect_changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore dependencies - TwitPoster.EmailSender
        run: dotnet restore ./TwitPoster.EmailSender

      - name: Build - TwitPoster.EmailSender
        run: dotnet build --no-restore ./TwitPoster.EmailSender -c Release

      - name: Test - TwitPoster.EmailSender
        env:
          ASPNETCORE_ENVIRONMENT: Production
        run: dotnet test --no-build --verbosity normal ./TwitPoster.EmailSender -c Release

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: publish image
        run: dotnet publish ./TwitPoster.EmailSender/src/TwitPoster.EmailSender/TwitPoster.EmailSender.csproj /t:PublishContainer -r linux-x64

      - name: change image tag
        run: docker tag twitposter-emailsender ${{ env.twitposter_emailsender_image }}

      - name: Docker Push
        run: docker push ${{ env.twitposter_emailsender_image }}
        
  build_infra:
    name: 'Terraform copy artifacts'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Actions'
        uses: actions/checkout@v4
        
      - name: Upload terraform artifacts
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-artifacts
          path: ./terraform
          
          
          
  deploy_dev_infa:
    name: 'Terraform dev deployment'
    needs: build_infra
    uses: ./.github/workflows/shared-deploy.yml
    with:
      workspace: first
      environment: first
    secrets: inherit
    
  deploy_dev_twitposter:
    name: 'Twitposter app dev deployment'
    needs: [deploy_dev_infa, build_twitposter]
    uses: ./.github/workflows/shared-twitposter-deploy.yml
    with:
      environment: first
      twitposter_image: 'ghcr.io/wallyrion/twitposter:${{github.sha}}'
      APP_SERVICE_NAME: ${{ needs.deploy_dev_infa.outputs.APP_SERVICE_NAME }}
    secrets: inherit
    
  deploy_qa_infra:
    name: 'Terraform QA deployment'
    needs: deploy_dev_infa
    uses: ./.github/workflows/shared-deploy.yml
    with:
      workspace: second
      environment: second
    secrets: inherit

  deploy_qa_twitposter:
    name: 'Twitposter app qa deployment'
    needs: [ deploy_dev_twitposter, deploy_qa_infra ]
    uses: ./.github/workflows/shared-twitposter-deploy.yml
    with:
      environment: second
      twitposter_image: 'ghcr.io/wallyrion/twitposter:${{github.sha}}'
      APP_SERVICE_NAME: ${{ needs.deploy_qa_infra.outputs.APP_SERVICE_NAME }}
    secrets: inherit
