name: Build artifacts

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["master", "feature/terraform-env"]
  workflow_dispatch:

permissions:
  contents: 'read'
  packages: 'write'

env:
  twitposter_image: 'ghcr.io/wallyrion/twitposter:${{github.sha}}'

jobs:
  detect_changes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            temp:
              - 'temp/**'

      - if: steps.changes.outputs.temp == 'true'
        run: |
          echo "Changes were detected in 'temp/', running the step."
  
  build_twitposter:
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.temp == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Restore dependencies - TwitPoster
        run: dotnet restore ./TwitPoster
  
      - name: Build - TwitPoster
        run: dotnet build --no-restore ./TwitPoster -c Release
  
      - name: Test - TwitPoster
        env:
          ASPNETCORE_ENVIRONMENT: Production
        run: dotnet test --no-build --verbosity normal ./TwitPoster -c Release
  
      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: publish image
        run: dotnet publish ./TwitPoster/src/TwitPoster.Web/TwitPoster.Web.csproj /t:PublishContainer -r linux-x64
  
      - name: change image tag
        run: docker tag twitposter ${{ env.twitposter_image }}
  
      - name: Docker Push
        run: docker push ${{ env.twitposter_image }}