name: Build artifacts

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["master", "feature/terraform-env"]
  workflow_dispatch:

permissions:
  contents: 'read'
  packages: 'write'

env:
  twitposter_image: 'ghcr.io/wallyrion/twitposter:${{github.sha}}'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
        
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            temp:
              - 'temp/**'

      - if: steps.changes.outputs.temp == 'true'
        run: |
          echo "Changes were detected in 'temp/', running the step."
     
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Restore dependencies - TwitPoster
        run: dotnet restore ./TwitPoster

      - name: Build - TwitPoster
        run: dotnet build --no-restore ./TwitPoster -c Release
      
      - name: Test - TwitPoster
        env:
          ASPNETCORE_ENVIRONMENT: Production
        run: dotnet test --no-build --verbosity normal ./TwitPoster -c Release

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: publish image
        run: dotnet publish ./TwitPoster/src/TwitPoster.Web/TwitPoster.Web.csproj /t:PublishContainer -r linux-x64

      - name: change image tag
        run: docker tag twitposter ${{ env.twitposter_image }}

      - name: Docker Push
        run: docker push ${{ env.twitposter_image }}

  deploy_to_VM:
    runs-on: ubuntu-latest
    needs: build
    if: false
    environment:
      name: 'vm'
      url: http://twitposters.com/swagger/index.html

    steps:
      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull the image to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script:
            sudo docker pull ${{ env.twitposter_image}};
            sudo docker stop twitposter || true;
            sudo docker rm twitposter || true;
            sudo docker run -p 5000:8080 -d --name twitposter --restart unless-stopped -e "Secrets__ClientId=${{ secrets.KEYVAULT_CLIENT_ID }}" -e "Secrets__UseSecrets=true" -e "Secrets__ClientSecret=${{ secrets.KEYVAULT_CLIENT_SECRET }}" -e "Secrets__TenantId=${{ secrets.KEYVAULT_TENANT_ID }}" -e "Secrets__KeyVaultUri=${{ secrets.KEYVAULT_URI }}" ${{ env.twitposter_image }}
