name: Dependent Workflow

on:
  workflow_run:
    workflows: ["TTerraform Apply"]
    types:
      - completed

permissions:
  contents: read

jobs:
  dependent_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print GitHub Secret
        env:
          TEST_APP_PUBLISH_PROFILE: ${{ secrets.TEST_APP_PUBLISH_PROFILE }}
        run: |
          echo "TEST_APP_PUBLISH_PROFILE: $TEST_APP_PUBLISH_PROFILE"
