name: Deploy environment

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string
      workspace:
        description: 'The Terraform workspace'
        required: true
        type: string

permissions:
  contents: 'read'
  packages: 'write'


jobs:
  infra:
    environment: ${{ inputs.workspace }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4

      - name: 'Print Current Workspace'
        run: |
          echo "Current Workspace: ${{ inputs.workspace }}"

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: terraform-artifacts

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: 'Initialize Terraform'
        run: |
          terraform init \
            -backend-config="resource_group_name=tfstate-rg" \
            -backend-config="storage_account_name=tfstate12345" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="client_id=${{ secrets.ARM_CLIENT_ID }}" \
            -backend-config="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" \
            -backend-config="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" \
            -backend-config="tenant_id=${{ secrets.ARM_TENANT_ID }}" \
        working-directory:  ${{ github.workspace }}/terraform-artifacts

    

    