name: Deploy environment

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string
      workspace:
        description: 'The Terraform workspace'
        required: true
        type: string
    outputs:
      APP_SERVICE_NAME:
        description: 'APP_SERVICE_NAME'
        value: ${{ jobs.infra.outputs.APP_SERVICE_NAME }}

permissions:
  contents: 'read'
  packages: 'write'


jobs:
  infra:
    outputs:
      APP_SERVICE_NAME: ${{ steps.fetch_app_service_name.outputs.APP_SERVICE_NAME }}
      APP_SERVICE_NAME_EMAIL_SENDER: ${{ steps.fetch_app_service_name.outputs.APP_SERVICE_NAME_EMAIL_SENDER }}
    environment: ${{ inputs.workspace }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4

      - name: 'Print Current Workspace'
        run: |
          echo "Current Workspace: ${{ inputs.workspace }}"

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-artifacts

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: 'Initialize Terraform'
        run: |
          terraform init \
            -backend-config="resource_group_name=tfstate-rg" \
            -backend-config="storage_account_name=tfstate12345" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="client_id=${{ secrets.ARM_CLIENT_ID }}" \
            -backend-config="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" \
            -backend-config="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" \
            -backend-config="tenant_id=${{ secrets.ARM_TENANT_ID }}" \
        working-directory:  ./terraform

      - name: Select Terraform Workspace
        run: |
          terraform workspace select ${{ inputs.workspace }} || terraform workspace new ${{ inputs.workspace }}
        working-directory: ./terraform
        
      - name: Plan Terraform
        id: plan
        run: terraform plan -var="environment=${{ inputs.environment }}" -out=tfplan
        working-directory: ./terraform

      - name: 'Apply Terraform'
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform
        
      - name: 'Fetch App Service Name'
        id: fetch_app_service_name
        run: echo |
          "APP_SERVICE_NAME=$(terraform output -raw app_service_name)" >> $GITHUB_OUTPUT
          "APP_SERVICE_NAME_EMAIL_SENDER=$(terraform output -raw emailsender_app_service_name)" >> $GITHUB_OUTPUT
        working-directory: ./terraform

      - name: 'Fetch Publish Profile Command'
        id: fetch_publish_profile
        run: |
          # Debugging output to see the command being run
          echo "Running terraform output command"
          terraform output -raw publish_profile_command

          # Fetch the publish profile command from Terraform output
          PUBLISH_PROFILE_COMMAND=$(terraform output -raw publish_profile_command)

          # Debugging output to see the command fetched from Terraform
          echo "Fetched Publish Profile Command: $PUBLISH_PROFILE_COMMAND"

          # Execute the fetched command and save the output to a file
          echo "Executing Publish Profile Command"
          eval $PUBLISH_PROFILE_COMMAND > publish_profile.xml

          # Debugging output to check the contents of the publish profile file
          echo "Contents of publish_profile.xml:"
          cat publish_profile.xml

          # Mask the contents of the publish profile file
          echo "::add-mask::$(cat publish_profile.xml)"

          # Set the environment variable with the contents of the publish profile file
          echo "PUBLISH_PROFILE_CONTENT=$(cat publish_profile.xml)" >> $GITHUB_ENV
        working-directory: ./terraform
        
      - name: 'Fetch Publish Profile Command for email sender'
        id: fetch_publish_profile_email_sender
        run: |
          # Debugging output to see the command being run
          echo "Running terraform output command"
          terraform output -raw emailsender_publish_profile_command

          # Fetch the publish profile command from Terraform output
          PUBLISH_PROFILE_COMMAND=$(terraform output -raw emailsender_publish_profile_command)

          # Debugging output to see the command fetched from Terraform
          echo "Fetched Publish Profile Command: $PUBLISH_PROFILE_COMMAND"

          # Execute the fetched command and save the output to a file
          echo "Executing Publish Profile Command"
          eval $PUBLISH_PROFILE_COMMAND > publish_profile.emailsender.xml

          # Debugging output to check the contents of the publish profile file
          echo "Contents of publish_profile.xml:"
          cat publish_profile.emailsender.xml

          # Mask the contents of the publish profile file
          echo "::add-mask::$(cat publish_profile.emailsender.xml)"

          # Set the environment variable with the contents of the publish profile file
          echo "PUBLISH_PROFILE_CONTENT=$(cat publish_profile.xml)" >> $GITHUB_ENV
        working-directory: ./terraform

      - name: 'Install GitHub CLI'
        run: sudo apt-get install -y gh

      - name: 'Set GitHub Secret'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_SECRETS_MANIPULATOR }}
        run: |
          echo "Setting GitHub Secret TEST_APP_PUBLISH_PROFILE"
          SECRET_CONTENT=$(cat ./terraform/publish_profile.xml)
          SECRET_CONTENT_EMAIL_SENDER=$(cat ./terraform/publish_profile.emailsender.xml)
          gh secret set TEST_APP_PUBLISH_PROFILE --body "$SECRET_CONTENT" --env ${{ inputs.environment }}
          gh secret set TEST_APP_PUBLISH_PROFILE_EMAIL_SENDER --body "SECRET_CONTENT_EMAIL_SENDER" --env ${{ inputs.environment }}
    