name: Deploy environment

on:
  workflow_call:
    inputs:
      deploy_twitposter:
        description: 'Indicates if the Twitposter app should be deployed'
        required: false
        type: string
        
      deploy_email_sender:
        description: 'Indicates if the Email sender app should be deployed'
        required: false
        type: string
        
      deploy_functions:
        description: 'Indicates if the functions app should be deployed'
        required: false
        type: string
      
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string
      workspace:
        description: 'The Terraform workspace'
        required: true
        type: string


permissions:
  contents: 'read'
  packages: 'write'
  actions: read

jobs:
  infra:
    name: 'Terraform [${{ inputs.environment }}]'
    uses: ./.github/workflows/shared.infrastructure.deploy.yml
    with:
      workspace: ${{ inputs.workspace }}
      environment: ${{ inputs.environment }}
    secrets: inherit
  
  deploy_twitposter_1:
    if: ${{ inputs.deploy_twitposter == 'true' }}
    needs: [ infra ]
    uses: ./.github/workflows/shared.twitposter.deploy.yml
    with:
      environment: ${{ inputs.environment }}
      twitposter_image: 'ghcr.io/wallyrion/twitposter:${{github.sha}}'
      APP_SERVICE_NAME: ${{ needs.infra.outputs.APP_SERVICE_NAME }}
    secrets: inherit
    
  deploy_email_sender:
    if: ${{ inputs.deploy_email_sender == 'true' }}
    needs: [ infra ]
    uses: ./.github/workflows/shared.twitposter-emailsender.deploy.yml
    with:
      environment: ${{ inputs.environment }}
      image: 'ghcr.io/wallyrion/twitposter-emailsender:${{github.sha}}'
      APP_SERVICE_NAME: ${{ needs.infra.outputs.APP_SERVICE_NAME_EMAIL_SENDER }}
    secrets: inherit

  deploy_dev_functions:
    if: ${{ inputs.deploy_functions == 'true' }}
    needs: [ infra ]
    uses: ./.github/workflows/shared.functions.deploy.yml
    with:
      environment: ${{ inputs.environment }}
      APP_SERVICE_NAME: ${{ needs.infra.outputs.APP_SERVICE_NAME_FUNCTIONS }}
    secrets: inherit
    
  wait_for_deployment:
    needs: [ infra ]
    runs-on: ubuntu-latest
    steps:
    - name: 'Wait for deployment'
      uses: yogeshlonkar/wait-for-jobs@v0
      with:
        gh-token: ${{ secrets.GITHUB_TOKEN }}
        ignore-skipped: 'true'
        interval: '3000'
        no-max-ttl: 'true'
        ttl: '60'
        jobs: |
          Full prod deployment / deploy_twitposter_1
          deploy_email_sender
          deploy_dev_functions
        
  run_e2e_tests:
    needs: wait_for_deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Restore dependencies - TwitPoster
        run: dotnet restore ./TwitPoster

      - name: Test - TwitPoster
        env:
          ASPNETCORE_ENVIRONMENT: Production
          TWITPOSTER_API_BASE_URL: 'https://twitposter-production-appservice.azurewebsites.net'
        run: dotnet test --verbosity normal ./TwitPoster.AutoTests -c Release
