name: Deploy environment

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string
      twitposter_image:
        description: 'The image to deploy to'
        required: true
        type: string
      APP_SERVICE_NAME:
        description: 'The image to deploy to'
        required: true
        type: string


permissions:
  contents: 'read'
  packages: 'write'


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}/swagger/index.html
    
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ inputs.APP_SERVICE_NAME }}
          publish-profile: ${{ secrets.TEST_APP_PUBLISH_PROFILE }}
          images: ${{ inputs.twitposter_image }}

      - name: Trigger Azure WebHook
        run: |
          curl -X POST $WEBHOOK_URL
        env:
          WEBHOOK_URL: ${{ secrets.TEST_APP_PUBLISH_PROFILE }}
        shell: bashraform@v3