name: Deploy environment

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string
      APP_SERVICE_NAME:
        description: 'name of the function app'
        required: true
        type: string


permissions:
  contents: 'read'
  packages: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: functions-artifacts
          
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name:  ${{ inputs.APP_SERVICE_NAME }}
          package: '.'