name: Deploy environment

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string
      APP_SERVICE_NAME:
        description: 'name of the function app'
        required: true
        type: string


permissions:
  contents: 'read'
  packages: 'write'

jobs:
  deploy:
    env:
      AZURE_FUNCTIONAPP_PACKAGE_PATH: './TwitPoster.Functions/TwitPoster.Functions'
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}

    steps:

      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          dotnet publish --configuration Release --output ./output
          popd
          
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name:  ${{ inputs.APP_SERVICE_NAME }}
          package: '.'