name: Build & deploy - TwitPoster.EmailSender


on:
  push:
    branches: ["master"]
    paths:
      - "TwitPoster.EmailSender/**"
      - ".github/workflows/TwitPoster.EmailSender.deploy.yml"
env:
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
      - name: Restore dependencies - TwitPoster.EmailSender
        run: dotnet restore ./TwitPoster.EmailSender
      - name: Build - TwitPoster.EmailSender
        run: dotnet build --no-restore ./TwitPoster.EmailSender -c Release
      - name: Test - TwitPoster.EmailSender
        env:
          ASPNETCORE_ENVIRONMENT: Production
        run: dotnet test --no-build --verbosity normal ./TwitPoster.EmailSender

      - name: publish
        run: dotnet publish ./TwitPoster.EmailSender/src/TwitPoster.EmailSender/TwitPoster.EmailSender.csproj -c Release --no-build -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: TwitPoster.EmailSender
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
 
  deploy_prod:
    needs: build
    environment: 'prod'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: TwitPoster.EmailSender
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deployment to twitposter
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_EMAIL_SENDER }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_EMAIL_SENDER }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}