name: Build & Test - TwitPoster.EmailSender


on:
  pull_request:
    branches: ["master"]
    paths:
      - "TwitPoster.EmailSender/**"
      - ".github/workflows/TwitPoster.EmailSender.build.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Restore dependencies - TwitPoster.EmailSender
        run: dotnet restore ./TwitPoster.EmailSender
        
      - name: Build - TwitPoster.EmailSender
        run: dotnet build --no-restore ./TwitPoster.EmailSender -c Release
        
      - name: Test - TwitPoster.EmailSender
        env:
          ASPNETCORE_ENVIRONMENT: Production
        run: dotnet test --no-build --verbosity normal ./TwitPoster.EmailSender -c Release
