name: terraform

on:
  push:
    branches: ["master", "terraform-init"]
  workflow_dispatch:

permissions:
  contents: 'read'
  packages: 'write'

env:
  twitposter_image: 'ghcr.io/wallyrion/twitposter:latest'


jobs:
  terraform:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest
    environment: prod  # Specify the environment here
    
    steps:
      - name: 'Checkout GitHub Actions'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: 'Initialize Terraform'
        run: terraform init
        working-directory: ./terraform

      - name: 'Plan Terraform'
        id: plan
        run: terraform plan -out=tfplan
        working-directory: ./terraform

      - name: 'Apply Terraform'
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform

      - name: 'Fetch App Service Name'
        id: fetch_app_service_name
        run: echo "APP_SERVICE_NAME=$(terraform output -raw app_service_name)" >> $GITHUB_ENV
        working-directory: ./terraform

      - name: 'Fetch Publish Profile Command'
        id: fetch_publish_profile
        run: |
          eval $(terraform output -raw publish_profile_command) > publish_profile.xml
          echo "::add-mask::$(cat publish_profile.xml)"
          echo "TEST_APP_PUBLISH_PROFILE=$(cat publish_profile.xml)" >> $GITHUB_ENV
        working-directory: ./terraform

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Set GitHub Secret
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_SECRETS_MANIPULATOR }}
        run: |
          cat publish_profile.xml | gh secret set TEST_APP_PUBLISH_PROFILE --env prod
        
        
  build:
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Restore dependencies - TwitPoster
        run: dotnet restore ./TwitPoster

      - name: Build - TwitPoster
        run: dotnet build --no-restore ./TwitPoster -c Release

      - name: Test - TwitPoster
        env:
          ASPNETCORE_ENVIRONMENT: Production
        run: dotnet test --no-build --verbosity normal ./TwitPoster -c Release

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: publish image
        run: dotnet publish ./TwitPoster/src/TwitPoster.Web/TwitPoster.Web.csproj /t:PublishContainer -r linux-x64

      - name: change image tag
        run: docker tag twitposter ${{ env.twitposter_image }}

      - name: Docker Push
        run: docker push ${{ env.twitposter_image }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'prod'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}/swagger/index.html

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_SERVICE_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_TWITPOSTER }}
          images: ${{ env.twitposter_image }}

      - name: Trigger Azure WebHook
        run: |
          curl -X POST $WEBHOOK_URL
        env:
          WEBHOOK_URL: ${{ secrets.AZURE_WEBHOOK_URL_TWITPOSTER }}
        shell: bash
  