name: Build and deploy .NET Core application to Function App twitposter-dev1-functionapp
on:
  pull_request:
    branches:
    - master
env:
  AZURE_FUNCTIONAPP_NAME: twitposter-dev1-functionapp
  AZURE_FUNCTIONAPP_PACKAGE_PATH: TwitPoster.Functions/published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 9.x
  WORKING_DIRECTORY: Twitposter.TestFunctions/TwitPoster.Functions
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
      
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        scm-do-build-during-deployment: true
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
      
