name: terraform

on:
  push:
    branches: ["master", "terraform-init"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write  # Allows using the OpenID Connect (OIDC) token
  actions: write

jobs:
  terraform:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest
    environment: prod  # Specify the environment here
    
    steps:
      - name: 'Checkout GitHub Actions'
        uses: actions/checkout@v4
        
        
  dependent_job:
    needs: terraform
    runs-on: ubuntu-latest
    environment: prod  # Specify the environment here
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print GitHub Secret
        env:
          TEST_APP_PUBLISH_PROFILE: ${{ secrets.TEST_APP_PUBLISH_PROFILE }}
        run: |
          echo "TEST_APP_PUBLISH_PROFILE: $TEST_APP_PUBLISH_PROFILE"

