name: 'Terraform Deploy'

on:
  push:
    branches: ["master", "terraform-init"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write  # Allows using the OpenID Connect (OIDC) token
  actions: write

jobs:
  terraform:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Actions'
        uses: actions/checkout@v4