name: Build & Test - TwitPoster

on:
  pull_request:
    branches: ["master"]
    paths:
      - "TwitPoster/**"
      - ".github/workflows/TwitPoster.build.yml"

permissions:
  contents: 'read'
  packages: 'write'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Restore dependencies - TwitPoster
        run: dotnet restore ./TwitPoster
        
      - name: Build - TwitPoster
        run: dotnet build --no-restore ./TwitPoster -c Release

      - name: Test - TwitPoster
        env:
          ASPNETCORE_ENVIRONMENT: Production
        run: dotnet test --no-build --verbosity normal ./TwitPoster -c Release
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        
      - name: publish image to docker hub
        run: dotnet publish ./TwitPoster/src/TwitPoster.Web/TwitPoster.Web.csproj /t:PublishContainer -r linux-x64


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
    
    steps:

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'twitposter'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_TWITPOSTER }}
          images: 'oleksiikorniienko/twitposter:latest'