name: 'Terraform Deploy'

on:
  push:
    branches: ["master", "terraform-init"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  secrets: write  # Allows setting secrets


jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Actions'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: 'Initialize Terraform'
        run: terraform init
        working-directory: ./terraform

      - name: 'Plan Terraform'
        id: plan
        run: terraform plan -out=tfplan
        working-directory: ./terraform


      - name: 'Apply Terraform'
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform

      - name: 'Fetch Publish Profile Command'
        id: fetch_publish_profile
        run: |
          eval $(terraform output -raw publish_profile_command) > publish_profile.xml
          echo "::add-mask::$(cat publish_profile.xml)"
          echo "TEST_APP_PUBLISH_PROFILE=$(cat publish_profile.xml)" >> $GITHUB_ENV
        working-directory: ./terraform

      - name: 'Set GitHub Secret'
        run: |
          echo "${{ env.TEST_APP_PUBLISH_PROFILE }}" | gh secret set TEST_APP_PUBLISH_PROFILE
        env:
          TEST_APP_PUBLISH_PROFILE: ${{ env.TEST_APP_PUBLISH_PROFILE }}