name: Build & Test - docker hub - TwitPoster

on:
  pull_request:
    branches: ["master"]
    paths:
      - "TwitPoster/**"
      - ".github/workflows/TwitPoster.build-docker-hub.yml"

permissions:
  contents: 'read'
  packages: 'write'

env:
  twitposter-image: 'oleksiikorniienko/twitposter:latest'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Restore dependencies - TwitPoster
        run: dotnet restore ./TwitPoster
        
      - name: Build - TwitPoster
        run: dotnet build --no-restore ./TwitPoster -c Release

      - name: Test - TwitPoster
        env:
          ASPNETCORE_ENVIRONMENT: Production
        run: dotnet test --no-build --verbosity normal ./TwitPoster -c Release
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        
      - name: publish image
        run: dotnet publish ./TwitPoster/src/TwitPoster.Web/TwitPoster.Web.csproj /t:PublishContainer -r linux-x64
        
      - name: change image tag 
        run: docker tag twitposter:latest ${{ env.twitposter-image }}
      
      - name: Docker Push
        run: docker push ${{ env.twitposter-image }}


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'prod'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}/swagger/index.html
      
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: experiment-1-twitposter
          publish-profile: ${{ secrets.AZURE_WEBAPP_1_PUBLISH_PROFILE }}
          images: ${{ env.twitposter-image }}
          
      - name: Trigger Azure WebHook
        run: |
          curl -X POST $WEBHOOK_URL
        env:
          WEBHOOK_URL: ${{ secrets.TWITPOSTER_1_WEBHOOK_URL }}
        shell: bash