name: Build, Test & Deploy - TwitPoster

on:
  push:
    branches: ["master"]
    paths:
      - "TwitPoster/**"
      - ".github/workflows/build-deploy.yml"
      - ".github/workflows/build.yml"

  repository_dispatch:

env:
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Restore dependencies - TwitPoster
        run: dotnet restore ./TwitPoster
        
      - name: Build - TwitPoster
        run: dotnet build --no-restore ./TwitPoster -c Release
        
      - name: Test - TwitPoster
        run: dotnet test --no-build --verbosity normal ./TwitPoster -c Release
        
      - name: publish
        run: dotnet publish ./TwitPoster/src/TwitPoster.Web/TwitPoster.Web.csproj -c Release --no-build -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: TwitPoster
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy_dev:
    needs: build
    environment: 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: TwitPoster
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deployment to twitposter
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_TWITPOSTER }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_TWITPOSTER }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  
  deploy_prod:
    needs: build
    if: github.ref == 'refs/heads/master'
    environment: 'prod'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: TwitPoster
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deployment to twitposter
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_TWITPOSTER }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_TWITPOSTER }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}