name: Build & Test - TwitPoster.Shared

on:
  push:
    branches: ["master", "experiments/dynamic-version"]
    paths:
      - "TwitPoster.Shared/**"
      - ".github/workflows/TwitPoster.Shared.yml"
  pull_request:
    branches: ["master"]
    paths:
      - "TwitPoster.Shared/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies - TwitPoster.Shared
        run: dotnet restore ./TwitPoster.Shared
     
      - name: Build - TwitPoster.Shared
        run: dotnet build --no-restore ./TwitPoster.Shared --configuration Release --nologo
      - name: Test - TwitPoster.Shared
        run: dotnet test --no-build --verbosity normal ./TwitPoster.Shared

      - name: Calculate version and create tag if needed
        id: version
        run: |
          $xml = [xml](Get-Content ./TwitPoster.Shared/TwitPoster.Shared/TwitPoster.Shared.csproj)
          $majorMinorVersion = $xml.Project.PropertyGroup.Version
          Write-Host "Major/minor version from csproj: '$majorMinorVersion'"
          
          $majorMinorVersion =  ($majorMinorVersion -split '\s') -join ''
          Write-Host "Trimmed major/minor version: '$majorMinorVersion'"
          
          git fetch --tags
          git fetch --all
          $versionTags = git tag --list "shared-version-*"
          Write-Host "tags: $versionTags"

          $commitCount = 0
          
          if ($versionTags) {
            $mostRecentTag = $versionTags | Sort-Object -Descending | Select-Object -First 1
            Write-Host "mostRecentTag tag: $mostRecentTag"
          
            $commitsCountHardcoded = git rev-list --count "shared-version-1.2"..HEAD
            Write-Host "commits count hardcoded tag: $commitsCountHardcoded"
          
            $lastTagVersion = $mostRecentTag -replace 'shared-version-',''
            $commitCount = git rev-list --count $HEAD..$mostRecentTag

            $commitTag = git rev-parse $mostRecentTag
            Write-Host "$mostRecentTag commit: $commitTag"
          
            $commitMessageMostRecentTag = git show -s --format=%s $mostRecentTag
            Write-Host "Commit message for the most recent tag ($mostRecentTag): $commitMessageMostRecentTag"
              
            $commitHead = git rev-parse HEAD
            Write-Host "HEAD commit: $commitHead"
          
            $commitMessageHEAD = git show -s --format=%s HEAD
            Write-Host "Commit message for HEAD: $commitMessageHEAD"
          
            $commitCount = (git cherry $mostRecentTag HEAD).Length
            Write-Host "Commit Count using cherry: $($commitCount)"
          
            $commitCount = git log --oneline $mostRecentTag..HEAD | Measure-Object -Line
            Write-Host "Commit Count: $($commitCount.Lines)"
          
            #commitsBewtween = git rev-list $mostRecentTag..HEAD
            Write-Host "commitsBewtween: $commitsBewtween"
          
            #commitsBewtween = git rev-list $mostRecentTag...HEAD
            Write-Host "commitsBewtween 3 dots: $commitsBewtween"
          
           #commitsBewtween = git rev-list $commitTag..$commitHead
            Write-Host "commitsBewtween: $commitsBewtween"
          
            #commitsBewtween = git rev-list $commitTag...$commitHead
            Write-Host "commitsBewtween 3 dots: $commitsBewtween"

            $commitCount = git rev-list --count 6f85f1c48cae0d6c2394a0c0e9e05599563f4cbf..24b542eb6f92818deea76778a0f16c8ee64cc3d9

            $commitCount = git rev-list --first-parent --count $mostRecentTag..HEAD
            Write-Host "Commit count since last tag: $commitCount"
          
            $commitCount = git rev-list HEAD ^$mostRecentTag --pretty=oneline --count
            Write-Host "Commit count Another ONE LINER : $commitCount"
          
            #commitsBewtween = git rev-list 6f85f1c48cae0d6c2394a0c0e9e05599563f4cbf..24b542eb6f92818deea76778a0f16c8ee64cc3d9
            Write-Host "commitsBewtween: $commitsBewtween"

          } else {
            $lastTagVersion = "0.0"
          }

          Write-Host "most recent tag: $lastTagVersion"

          if ($majorMinorVersion -ne $lastTagVersion) {
            Write-Host "New version detected, creating a new tag..."
            git tag "shared-version-$majorMinorVersion"
            git push origin "shared-version-$majorMinorVersion"
            $commitCount = 0; 
          }

          Write-Host "Commit count since last tag: $commitCount"

          $version = "$majorMinorVersion.$commitCount"
          Write-Host "Package version: $version"

          echo "VERSION=${version}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh
      - name: Pack
        run: dotnet pack ./TwitPoster.Shared /p:PackageVersion="${{ env.VERSION }}" --no-build -o out --configuration Release --nologo
      - name: Push
        run: dotnet nuget push "out/**/*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
