name: Build & Test - TwitPoster

on:
  pull_request:
    branches: ["master"]
    paths:
      - "TwitPoster/**"
      - ".github/workflows/TwitPoster.build.yml"
      - ".github/workflows/TwitPoster.deploy.yml"
      - ".github/workflows/full-deploy.yml"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
        
      - name: Restore dependencies - TwitPoster
        run: dotnet restore ./TwitPoster --locked-mode
        
      - name: Replace CurrentImageTag in appsettings.json
        run: |
          GITHUB_SHA_SHORT=${{ github.sha }}
          sed -i 's/"CurrentImageTag": "latest"/"CurrentImageTag": "'${GITHUB_SHA_SHORT}'"/' ./TwitPoster/src/TwitPoster.Web/appsettings.json

      - name: Verify appsettings.json
        run: cat ./TwitPoster/src/TwitPoster.Web/appsettings.json

      - name: Build - TwitPoster
        run: dotnet build --no-restore ./TwitPoster -c Release

      - name: Test - TwitPoster
        env:
          ASPNETCORE_ENVIRONMENT: Production
        run: dotnet test --no-build --verbosity normal ./TwitPoster -c Release