name: terraform

on:
  push:
    branches: ["master", "terraform-init"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write  # Allows using the OpenID Connect (OIDC) token
  actions: write

jobs:
  terraform:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest
    environment: prod  # Specify the environment here
    
    steps:
      - name: 'Checkout GitHub Actions'
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh
  
      - name: Set GitHub Secret
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_SECRETS_MANIPULATOR }}
        run: |
          echo "hardcoded_publish_profile_value" | gh secret set TEST_APP_PUBLISH_PROFILE --env prod
        
        
  dependent_job:
    needs: terraform
    runs-on: ubuntu-latest
    environment: prod  # Specify the environment here
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print GitHub Secret
        env:
          TEST_APP_PUBLISH_PROFILE: ${{ secrets.TEST_APP_PUBLISH_PROFILE }}
        run: |
          echo "TEST_APP_PUBLISH_PROFILE: $TEST_APP_PUBLISH_PROFILE"

