name: Build & Test - TwitPoster

on:
  push:
    branches: ["master"]
    paths:
      - "TwitPoster/**"
      - ".github/workflows/TwitPoster.yml"
  pull_request:
    branches: ["master"]
    paths:
      - "TwitPoster/**"
      - ".github/workflows/TwitPoster.yml"


env:
  AZURE_WEBAPP_NAME: "twitposter-service"
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies - TwitPoster
        run: dotnet restore ./TwitPoster
      - name: Build - TwitPoster
        run: dotnet build --no-restore ./TwitPoster -c Release
      - name: Test - TwitPoster
        run: dotnet test --no-build --verbosity normal ./TwitPoster -c Release

      - name: publish
        run: dotnet publish ./TwitPoster/src/TwitPoster.Web/TwitPoster.Web.csproj -c Release --no-build -o ./publish/app
        
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: twitposter-service
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish/app
        
        
