name: Build & Test - TwitPoster.Shared

on:
  push:
    branches: ["master", "experiments/dynamic-version"]
    paths:
      - "TwitPoster.Shared/**"
      - ".github/workflows/TwitPoster.Shared.yml"
  pull_request:
    branches: ["master"]
    paths:
      - "TwitPoster.Shared/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies - TwitPoster.Shared
        run: dotnet restore ./TwitPoster.Shared
     
      - name: Build - TwitPoster.Shared
        run: dotnet build --no-restore ./TwitPoster.Shared --configuration Release --nologo
      - name: Test - TwitPoster.Shared
        run: dotnet test --no-build --verbosity normal ./TwitPoster.Shared

      - name: Fetch all history
        run: git fetch --prune --unshallow
        
      - name: Calculate version and create tag if needed
        id: version
        run: |
          $tagPrefix = "shared-version-"

          $xml = [xml](Get-Content ./TwitPoster.Shared/TwitPoster.Shared/TwitPoster.Shared.csproj)
          $majorMinorVersion = $xml.Project.PropertyGroup.Version
          $majorMinorVersion =  ($majorMinorVersion -split '\s') -join ''
          Write-Host "Major/minor version from TwitPoster.csproj: '$majorMinorVersion'"
          
          $versionTags = git tag --list "$tagPrefix*"
          Write-Host "Tags found: $versionTags"

          $commitCount = 0
          
          if ($versionTags) {
            $mostRecentTag = $versionTags | Sort-Object -Descending | Select-Object -First 1
            Write-Host "mostRecentTag tag: $mostRecentTag"
          
            $lastTagVersion = $mostRecentTag -replace $tagPrefix,''
            $commitCount = git rev-list --count $HEAD..$mostRecentTag

            $commitCount = git rev-list HEAD ^$mostRecentTag --pretty=oneline --count
            Write-Host "Commit count between current commit and last tag : $commitCount"
          } else {
            $lastTagVersion = "0.0"
          }

          Write-Host "Most recent version: $lastTagVersion"

          if ($majorMinorVersion -ne $lastTagVersion) {
            Write-Host "New version detected, creating a new tag..."
            git tag "$tagPrefix$majorMinorVersion"
            git push origin "$tagPrefix$majorMinorVersion"
            $commitCount = 0; 
          }

          Write-Host "Commit count since last tag: $commitCount"

          $version = "$majorMinorVersion.$commitCount"
          Write-Host "Package version: $version"

          echo "VERSION=${version}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh
      - name: Pack
        run: dotnet pack ./TwitPoster.Shared /p:PackageVersion="${{ env.VERSION }}" --no-build -o out --configuration Release --nologo
      - name: Push
        run: dotnet nuget push "out/**/*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
